FRS-908 - Add CI to PR's
IMGARENA/event-centre-operator-styles pull request #2
Opened 2021-01-26 14:41 UTC by footerz

## Changes
- Adds package json
- Adds stylelint
- Adds stylesheet check for CI
- Adds mandatory variables for UFC and Golf
- Adds new PR CI workflow

## Reference
Fixes [FRS-908]

2021-01-27 07:37 UTC, MrTibbles requested changes

2021-01-27 07:37 UTC, MrTibbles commented on README.md
> +The parent directory of the stylesheet will change depending on what event centre directory you place your stylesheet.
IMO this is not of interest to the intended audience of this README.

2021-01-27 07:37 UTC, MrTibbles commented on README.md
> +The /mandatory-variables directory houses the css variable names which MUST be present in each event centres stylesheet. This will be automatically checked for each PR raised.
This contradicts the implementation of variables being optionally overridden. If a variable is not overridden then it's value will be taken from the default values defined in the base.css file which is within each event repo. 
The variables are not mandatory, they are **available to be overridden**.

2021-01-27 07:37 UTC, MrTibbles commented on scripts/stylesheet-check.js
> +const variablesIncluded = (arr, target) => target.every(v => arr.includes(v));
Prefer meaningful variable names, please amend the use of `v`

2021-01-27 07:37 UTC, MrTibbles commented on scripts/stylesheet-check.js
> +                const rl = readline.createInterface({
Prefer meaningful variable names, please amend the use of `rl`

2021-01-27 07:37 UTC, MrTibbles commented on scripts/stylesheet-check.js
> +                    if (line.includes('--') && !line.includes('/*') && !line.includes('*/')) {
Consider using a regex pattern, would be neater IMO and faster

2021-01-27 07:37 UTC, MrTibbles commented on scripts/stylesheet-check.js
> +                    console.log('FAILURE: stylesheets/' + directory + '/' + file + ' is missing a mandatory ' + directory + ' css variable(s).');
Again, they are not mandatory, they are available to be overridden. As discussed, this script is sense checking the variables being passed in to check that only available variables are being used and they are spelt correctly. NOT that they are all being overridden.

2021-01-27 09:48 UTC, footerz commented on scripts/stylesheet-check.js
> +                    console.log('FAILURE: stylesheets/' + directory + '/' + file + ' is missing a mandatory ' + directory + ' css variable(s).');
Ok, so essentially we're just spell checking any supplied variables against the base ones. I was on a different page.

2021-01-27 13:14 UTC, footerz commented on README.md
> +The parent directory of the stylesheet will change depending on what event centre directory you place your stylesheet.
Sure. f28ad95

2021-01-27 13:21 UTC, footerz commented on README.md
> +The /mandatory-variables directory houses the css variable names which MUST be present in each event centres stylesheet. This will be automatically checked for each PR raised.
Sure! dc9c2d8

2021-01-27 13:53 UTC, footerz commented on scripts/stylesheet-check.js
> +                    console.log('FAILURE: stylesheets/' + directory + '/' + file + ' is missing a mandatory ' + directory + ' css variable(s).');
Here we go dd13e55

2021-01-27 13:53 UTC, footerz commented on scripts/stylesheet-check.js
> +const variablesIncluded = (arr, target) => target.every(v => arr.includes(v));
This no longer exists dd13e55

2021-01-27 13:53 UTC, footerz commented on scripts/stylesheet-check.js
> +                const rl = readline.createInterface({
Changed dd13e55

2021-01-27 15:06 UTC, footerz commented on scripts/stylesheet-check.js
> +                    if (line.includes('--') && !line.includes('/*') && !line.includes('*/')) {
Politely declining. 😂

2021-01-28 10:46 UTC, MrTibbles requested changes
For consistency and clarity please remove references to the variables being mandatory, as they are not.

2021-01-28 10:46 UTC, MrTibbles commented on event-centre-variables/golf.js
> +module.exports = mandatoryGolfVariables;
again, they are not mandatory, they are "supportedVariables"

2021-01-28 10:46 UTC, MrTibbles commented on event-centre-variables/ufc.js
> +const mandatoryUfcVariables = ['white', 'black'];
same as above

2021-01-28 10:46 UTC, MrTibbles commented on scripts/stylesheet-check.js
> +                    if (line.includes('--') && !line.includes('/*') && !line.includes('*/')) {
lols

2021-01-28 13:42 UTC, footerz commented on event-centre-variables/ufc.js
> +const mandatoryUfcVariables = ['white', 'black'];
430178a

2021-01-28 13:43 UTC, footerz commented on event-centre-variables/golf.js
> +module.exports = mandatoryGolfVariables;
430178a

2021-01-28 13:50 UTC, MrTibbles approved these changes

2021-01-28 13:52 UTC, merged